name: Deploy Web to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H 192.168.18.175 >> ~/.ssh/known_hosts
          ls -la ~/.ssh/

      - name: Test SSH Connection
        run: ssh -v virhan@192.168.18.175 'echo "SSH Connection successful"'

      - name: Deploy and Restart
        run: |
          ssh virhan@192.168.18.175 '
            cd /home/virhan/astra
            git pull origin main
            npm install
            npm run build
            
            # Set permissions
            sudo chown -R virhan:virhan .
            sudo chown -R www-data:www-data dist
            
            # Restart dengan PM2
            pm2 delete astra || true
            pm2 start npm --name "astra" -- run preview
            pm2 save
          '